services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: admin1234
      MINIO_SECRET_KEY: admin1234
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: backend
    stdin_open: true
    depends_on:
      - mongodb
      - minio
    volumes:
      - "T:/Python/Documents-Chatbot/backend/credentials.json:/app/credentials.json"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin1234
      - MINIO_SECRET_KEY=admin1234
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    ports:
      - "912:912"
    networks:
      - mynetwork

volumes:
  mongodata:

networks:
  mynetwork:
    driver: bridge
